
package lv.fis.zont.service.web;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "AppException", targetNamespace = "http://web.service.zont.fis.lv/")
public class AppException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private AppException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public AppException_Exception(String message, AppException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public AppException_Exception(String message, AppException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: lv.fis.zont.service.web.AppException
     */
    public AppException getFaultInfo() {
        return faultInfo;
    }

}
