
package lv.fis.zont.service.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubAgentWebService", targetNamespace = "http://web.service.zont.fis.lv/", wsdlLocation = "http://demo3.busticketpro.com/wse/SubAgentWebService?wsdl")
public class SubAgentWebService_Service
    extends Service
{

    private final static URL SUBAGENTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBAGENTWEBSERVICE_EXCEPTION;
    private final static QName SUBAGENTWEBSERVICE_QNAME = new QName("http://web.service.zont.fis.lv/", "SubAgentWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://demo3.busticketpro.com/wse/SubAgentWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUBAGENTWEBSERVICE_WSDL_LOCATION = url;
        SUBAGENTWEBSERVICE_EXCEPTION = e;
    }

    public SubAgentWebService_Service() {
        super(__getWsdlLocation(), SUBAGENTWEBSERVICE_QNAME);
    }

    public SubAgentWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBAGENTWEBSERVICE_QNAME, features);
    }

    public SubAgentWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SUBAGENTWEBSERVICE_QNAME);
    }

    public SubAgentWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBAGENTWEBSERVICE_QNAME, features);
    }

    public SubAgentWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubAgentWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubAgentWebService
     */
    @WebEndpoint(name = "SubAgentWebServicePort")
    public SubAgentWebService getSubAgentWebServicePort() {
        return super.getPort(new QName("http://web.service.zont.fis.lv/", "SubAgentWebServicePort"), SubAgentWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubAgentWebService
     */
    @WebEndpoint(name = "SubAgentWebServicePort")
    public SubAgentWebService getSubAgentWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web.service.zont.fis.lv/", "SubAgentWebServicePort"), SubAgentWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBAGENTWEBSERVICE_EXCEPTION!= null) {
            throw SUBAGENTWEBSERVICE_EXCEPTION;
        }
        return SUBAGENTWEBSERVICE_WSDL_LOCATION;
    }

}
