//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.01.13 at 05:10:51 PM EET
//

package com.gillsoft.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="group">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="stations">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="station" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="country_code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="threads">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="thread" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="stoppoints">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="stoppoint" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;simpleContent>
 *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                         &lt;attribute name="departure_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                         &lt;attribute name="station_code" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                         &lt;attribute name="station_code_system" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="station_title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="arrival_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                                       &lt;/extension>
 *                                                     &lt;/simpleContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="schedules">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="schedule">
 *                                                   &lt;complexType>
 *                                                     &lt;simpleContent>
 *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                                         &lt;attribute name="days" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="period_end_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="period_end_time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="period_start_date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="period_start_time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="times" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                         &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                                       &lt;/extension>
 *                                                     &lt;/simpleContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="carrier_code_system" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="carrier_title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="t_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="t_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"group"})
@XmlRootElement(name = "channel")
public class Channel implements Serializable {

	private static final long serialVersionUID = 2181021872517152853L;

  @XmlElement(required = true)
  protected Channel.Group group;
  @XmlAttribute(name = "t_type")
  protected String tType;
  @XmlAttribute(name = "version")
  protected Float version;
  @XmlAttribute(name = "timezone")
  protected String timezone;

  /**
   * Gets the value of the group property.
   * 
   * @return possible object is {@link Channel.Group }
   * 
   */
  public Channel.Group getGroup() {
    return group;
  }

  /**
   * Sets the value of the group property.
   * 
   * @param value allowed object is {@link Channel.Group }
   * 
   */
  public void setGroup(Channel.Group value) {
    this.group = value;
  }

  /**
   * Gets the value of the tType property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getTType() {
    return tType;
  }

  /**
   * Sets the value of the tType property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setTType(String value) {
    this.tType = value;
  }

  /**
   * Gets the value of the version property.
   * 
   * @return possible object is {@link Float }
   * 
   */
  public Float getVersion() {
    return version;
  }

  /**
   * Sets the value of the version property.
   * 
   * @param value allowed object is {@link Float }
   * 
   */
  public void setVersion(Float value) {
    this.version = value;
  }

  /**
   * Gets the value of the timezone property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getTimezone() {
    return timezone;
  }

  /**
   * Sets the value of the timezone property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setTimezone(String value) {
    this.timezone = value;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="stations">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="station" maxOccurs="unbounded" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;simpleContent>
   *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
   *                           &lt;attribute name="country_code" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                         &lt;/extension>
   *                       &lt;/simpleContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="threads">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="thread" maxOccurs="unbounded" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="stoppoints">
   *                               &lt;complexType>
   *                                 &lt;complexContent>
   *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                     &lt;sequence>
   *                                       &lt;element name="stoppoint" maxOccurs="unbounded" minOccurs="0">
   *                                         &lt;complexType>
   *                                           &lt;simpleContent>
   *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                                               &lt;attribute name="departure_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
   *                                               &lt;attribute name="station_code" type="{http://www.w3.org/2001/XMLSchema}int" />
   *                                               &lt;attribute name="station_code_system" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                                               &lt;attribute name="station_title" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                                               &lt;attribute name="arrival_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
   *                                             &lt;/extension>
   *                                           &lt;/simpleContent>
   *                                         &lt;/complexType>
   *                                       &lt;/element>
   *                                     &lt;/sequence>
   *                                   &lt;/restriction>
   *                                 &lt;/complexContent>
   *                               &lt;/complexType>
   *                             &lt;/element>
   *                             &lt;element name="schedules">
   *                               &lt;complexType>
   *                                 &lt;complexContent>
   *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                     &lt;sequence>
   *                                       &lt;element name="schedule">
   *                                         &lt;complexType>
   *                                           &lt;simpleContent>
   *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                                               &lt;attribute name="days" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                                               &lt;attribute name="period_end_date" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                                               &lt;attribute name="period_end_time" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                                               &lt;attribute name="period_start_date" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                                               &lt;attribute name="period_start_time" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                                               &lt;attribute name="times" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                                               &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                                             &lt;/extension>
   *                                           &lt;/simpleContent>
   *                                         &lt;/complexType>
   *                                       &lt;/element>
   *                                     &lt;/sequence>
   *                                   &lt;/restriction>
   *                                 &lt;/complexContent>
   *                               &lt;/complexType>
   *                             &lt;/element>
   *                           &lt;/sequence>
   *                           &lt;attribute name="carrier_code_system" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                           &lt;attribute name="carrier_title" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                           &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                           &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                           &lt;attribute name="t_type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}byte" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"stations", "threads"})
  public static class Group implements Serializable {

	private static final long serialVersionUID = -2706311170897557946L;

	@XmlElement(required = true)
    protected Channel.Group.Stations stations;
    @XmlElement(required = true)
    protected Channel.Group.Threads threads;
    @XmlAttribute(name = "code")
    protected Byte code;

    /**
     * Gets the value of the stations property.
     * 
     * @return possible object is {@link Channel.Group.Stations }
     * 
     */
    public Channel.Group.Stations getStations() {
      return stations;
    }

    /**
     * Sets the value of the stations property.
     * 
     * @param value allowed object is {@link Channel.Group.Stations }
     * 
     */
    public void setStations(Channel.Group.Stations value) {
      this.stations = value;
    }

    /**
     * Gets the value of the threads property.
     * 
     * @return possible object is {@link Channel.Group.Threads }
     * 
     */
    public Channel.Group.Threads getThreads() {
      return threads;
    }

    /**
     * Sets the value of the threads property.
     * 
     * @param value allowed object is {@link Channel.Group.Threads }
     * 
     */
    public void setThreads(Channel.Group.Threads value) {
      this.threads = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return possible object is {@link Byte }
     * 
     */
    public Byte getCode() {
      return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value allowed object is {@link Byte }
     * 
     */
    public void setCode(Byte value) {
      this.code = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="station" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="country_code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"station"})
    public static class Stations implements Serializable {

		private static final long serialVersionUID = -6499750547951492793L;

	protected List<Channel.Group.Stations.Station> station;

      /**
       * Gets the value of the station property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any
       * modification you make to the returned list will be present inside the JAXB object. This is
       * why there is not a <CODE>set</CODE> method for the station property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getStation().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list
       * {@link Channel.Group.Stations.Station }
       * 
       * 
       */
      public List<Channel.Group.Stations.Station> getStation() {
        if (station == null) {
          station = new ArrayList<Channel.Group.Stations.Station>();
        }
        return this.station;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;simpleContent>
       *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
       *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}int" />
       *       &lt;attribute name="country_code" type="{http://www.w3.org/2001/XMLSchema}string" />
       *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
       *     &lt;/extension>
       *   &lt;/simpleContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = {"value"})
      public static class Station implements Serializable {

		private static final long serialVersionUID = 5731644182580075989L;

		@XmlValue
        protected String value;
        @XmlAttribute(name = "code")
        protected Integer code;
        @XmlAttribute(name = "country_code")
        protected String countryCode;
        @XmlAttribute(name = "title")
        protected String title;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
          return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
          this.value = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return possible object is {@link Integer }
         * 
         */
        public Integer getCode() {
          return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value allowed object is {@link Integer }
         * 
         */
        public void setCode(Integer value) {
          this.code = value;
        }

        /**
         * Gets the value of the countryCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCountryCode() {
          return countryCode;
        }

        /**
         * Sets the value of the countryCode property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCountryCode(String value) {
          this.countryCode = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTitle() {
          return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setTitle(String value) {
          this.title = value;
        }

      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="thread" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="stoppoints">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="stoppoint" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="departure_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="station_code" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="station_code_system" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="station_title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="arrival_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="schedules">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="schedule">
     *                               &lt;complexType>
     *                                 &lt;simpleContent>
     *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                                     &lt;attribute name="days" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="period_end_date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="period_end_time" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="period_start_date" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="period_start_time" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="times" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                   &lt;/extension>
     *                                 &lt;/simpleContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="carrier_code_system" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="carrier_title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="t_type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"thread"})
    public static class Threads implements Serializable {

		private static final long serialVersionUID = -9133228157514426735L;

	protected List<Channel.Group.Threads.Thread> thread;

      /**
       * Gets the value of the thread property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any
       * modification you make to the returned list will be present inside the JAXB object. This is
       * why there is not a <CODE>set</CODE> method for the thread property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getThread().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list
       * {@link Channel.Group.Threads.Thread }
       * 
       * 
       */
      public List<Channel.Group.Threads.Thread> getThread() {
        if (thread == null) {
          thread = new ArrayList<Channel.Group.Threads.Thread>();
        }
        return this.thread;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="stoppoints">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                 &lt;sequence>
       *                   &lt;element name="stoppoint" maxOccurs="unbounded" minOccurs="0">
       *                     &lt;complexType>
       *                       &lt;simpleContent>
       *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
       *                           &lt;attribute name="departure_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
       *                           &lt;attribute name="station_code" type="{http://www.w3.org/2001/XMLSchema}int" />
       *                           &lt;attribute name="station_code_system" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                           &lt;attribute name="station_title" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                           &lt;attribute name="arrival_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
       *                         &lt;/extension>
       *                       &lt;/simpleContent>
       *                     &lt;/complexType>
       *                   &lt;/element>
       *                 &lt;/sequence>
       *               &lt;/restriction>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *         &lt;element name="schedules">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                 &lt;sequence>
       *                   &lt;element name="schedule">
       *                     &lt;complexType>
       *                       &lt;simpleContent>
       *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
       *                           &lt;attribute name="days" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                           &lt;attribute name="period_end_date" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                           &lt;attribute name="period_end_time" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                           &lt;attribute name="period_start_date" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                           &lt;attribute name="period_start_time" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                           &lt;attribute name="times" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                           &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
       *                         &lt;/extension>
       *                       &lt;/simpleContent>
       *                     &lt;/complexType>
       *                   &lt;/element>
       *                 &lt;/sequence>
       *               &lt;/restriction>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *       &lt;/sequence>
       *       &lt;attribute name="carrier_code_system" type="{http://www.w3.org/2001/XMLSchema}string" />
       *       &lt;attribute name="carrier_title" type="{http://www.w3.org/2001/XMLSchema}string" />
       *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}string" />
       *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" />
       *       &lt;attribute name="t_type" type="{http://www.w3.org/2001/XMLSchema}string" />
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = {"stoppoints", "schedules"})
      public static class Thread implements Serializable {

		private static final long serialVersionUID = -7364443837090259380L;

		@XmlElement(required = true)
        protected Channel.Group.Threads.Thread.Stoppoints stoppoints;
        @XmlElement(required = true)
        protected Channel.Group.Threads.Thread.Schedules schedules;
        @XmlAttribute(name = "carrier_code_system")
        protected String carrierCodeSystem;
        @XmlAttribute(name = "carrier_title")
        protected String carrierTitle;
        @XmlAttribute(name = "language")
        protected String language;
        @XmlAttribute(name = "title")
        protected String title;
        @XmlAttribute(name = "t_type")
        protected String tType;

        /**
         * Gets the value of the stoppoints property.
         * 
         * @return possible object is {@link Channel.Group.Threads.Thread.Stoppoints }
         * 
         */
        public Channel.Group.Threads.Thread.Stoppoints getStoppoints() {
          return stoppoints;
        }

        /**
         * Sets the value of the stoppoints property.
         * 
         * @param value allowed object is {@link Channel.Group.Threads.Thread.Stoppoints }
         * 
         */
        public void setStoppoints(Channel.Group.Threads.Thread.Stoppoints value) {
          this.stoppoints = value;
        }

        /**
         * Gets the value of the schedules property.
         * 
         * @return possible object is {@link Channel.Group.Threads.Thread.Schedules }
         * 
         */
        public Channel.Group.Threads.Thread.Schedules getSchedules() {
          return schedules;
        }

        /**
         * Sets the value of the schedules property.
         * 
         * @param value allowed object is {@link Channel.Group.Threads.Thread.Schedules }
         * 
         */
        public void setSchedules(Channel.Group.Threads.Thread.Schedules value) {
          this.schedules = value;
        }

        /**
         * Gets the value of the carrierCodeSystem property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCarrierCodeSystem() {
          return carrierCodeSystem;
        }

        /**
         * Sets the value of the carrierCodeSystem property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCarrierCodeSystem(String value) {
          this.carrierCodeSystem = value;
        }

        /**
         * Gets the value of the carrierTitle property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCarrierTitle() {
          return carrierTitle;
        }

        /**
         * Sets the value of the carrierTitle property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCarrierTitle(String value) {
          this.carrierTitle = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLanguage() {
          return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setLanguage(String value) {
          this.language = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTitle() {
          return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setTitle(String value) {
          this.title = value;
        }

        /**
         * Gets the value of the tType property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getTType() {
          return tType;
        }

        /**
         * Sets the value of the tType property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setTType(String value) {
          this.tType = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="schedule">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="days" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="period_end_date" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="period_end_time" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="period_start_date" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="period_start_time" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="times" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {"schedule"})
        public static class Schedules implements Serializable {

			private static final long serialVersionUID = 765467997910237805L;

		@XmlElement(required = true)
          protected Channel.Group.Threads.Thread.Schedules.Schedule schedule;

          /**
           * Gets the value of the schedule property.
           * 
           * @return possible object is {@link Channel.Group.Threads.Thread.Schedules.Schedule }
           * 
           */
          public Channel.Group.Threads.Thread.Schedules.Schedule getSchedule() {
            return schedule;
          }

          /**
           * Sets the value of the schedule property.
           * 
           * @param value allowed object is {@link Channel.Group.Threads.Thread.Schedules.Schedule }
           * 
           */
          public void setSchedule(Channel.Group.Threads.Thread.Schedules.Schedule value) {
            this.schedule = value;
          }

          /**
           * <p>
           * Java class for anonymous complex type.
           * 
           * <p>
           * The following schema fragment specifies the expected content contained within this
           * class.
           * 
           * <pre>
           * &lt;complexType>
           *   &lt;simpleContent>
           *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
           *       &lt;attribute name="days" type="{http://www.w3.org/2001/XMLSchema}string" />
           *       &lt;attribute name="period_end_date" type="{http://www.w3.org/2001/XMLSchema}string" />
           *       &lt;attribute name="period_end_time" type="{http://www.w3.org/2001/XMLSchema}string" />
           *       &lt;attribute name="period_start_date" type="{http://www.w3.org/2001/XMLSchema}string" />
           *       &lt;attribute name="period_start_time" type="{http://www.w3.org/2001/XMLSchema}string" />
           *       &lt;attribute name="times" type="{http://www.w3.org/2001/XMLSchema}string" />
           *       &lt;attribute name="timezone" type="{http://www.w3.org/2001/XMLSchema}string" />
           *     &lt;/extension>
           *   &lt;/simpleContent>
           * &lt;/complexType>
           * </pre>
           * 
           * 
           */
          @XmlAccessorType(XmlAccessType.FIELD)
          @XmlType(name = "", propOrder = {"value"})
          public static class Schedule implements Serializable {

			private static final long serialVersionUID = -7845143292922964887L;

			@XmlValue
            protected String value;
            @XmlAttribute(name = "days")
            protected String days;
            @XmlAttribute(name = "period_end_date")
            protected String periodEndDate;
            @XmlAttribute(name = "period_end_time")
            protected String periodEndTime;
            @XmlAttribute(name = "period_start_date")
            protected String periodStartDate;
            @XmlAttribute(name = "period_start_time")
            protected String periodStartTime;
            @XmlAttribute(name = "times")
            protected String times;
            @XmlAttribute(name = "timezone")
            protected String timezone;

            /**
             * Gets the value of the value property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getValue() {
              return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setValue(String value) {
              this.value = value;
            }

            /**
             * Gets the value of the days property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getDays() {
              return days;
            }

            /**
             * Sets the value of the days property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setDays(String value) {
              this.days = value;
            }

            /**
             * Gets the value of the periodEndDate property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getPeriodEndDate() {
              return periodEndDate;
            }

            /**
             * Sets the value of the periodEndDate property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setPeriodEndDate(String value) {
              this.periodEndDate = value;
            }

            /**
             * Gets the value of the periodEndTime property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getPeriodEndTime() {
              return periodEndTime;
            }

            /**
             * Sets the value of the periodEndTime property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setPeriodEndTime(String value) {
              this.periodEndTime = value;
            }

            /**
             * Gets the value of the periodStartDate property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getPeriodStartDate() {
              return periodStartDate;
            }

            /**
             * Sets the value of the periodStartDate property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setPeriodStartDate(String value) {
              this.periodStartDate = value;
            }

            /**
             * Gets the value of the periodStartTime property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getPeriodStartTime() {
              return periodStartTime;
            }

            /**
             * Sets the value of the periodStartTime property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setPeriodStartTime(String value) {
              this.periodStartTime = value;
            }

            /**
             * Gets the value of the times property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getTimes() {
              return times;
            }

            /**
             * Sets the value of the times property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setTimes(String value) {
              this.times = value;
            }

            /**
             * Gets the value of the timezone property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getTimezone() {
              return timezone;
            }

            /**
             * Sets the value of the timezone property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setTimezone(String value) {
              this.timezone = value;
            }

          }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="stoppoint" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *                 &lt;attribute name="departure_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="station_code" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="station_code_system" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="station_title" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="arrival_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {"stoppoint"})
        public static class Stoppoints implements Serializable {

			private static final long serialVersionUID = 6713188109934113257L;

		protected List<Channel.Group.Threads.Thread.Stoppoints.Stoppoint> stoppoint;

          /**
           * Gets the value of the stoppoint property.
           * 
           * <p>
           * This accessor method returns a reference to the live list, not a snapshot. Therefore
           * any modification you make to the returned list will be present inside the JAXB object.
           * This is why there is not a <CODE>set</CODE> method for the stoppoint property.
           * 
           * <p>
           * For example, to add a new item, do as follows:
           * 
           * <pre>
           * getStoppoint().add(newItem);
           * </pre>
           * 
           * 
           * <p>
           * Objects of the following type(s) are allowed in the list
           * {@link Channel.Group.Threads.Thread.Stoppoints.Stoppoint }
           * 
           * 
           */
          public List<Channel.Group.Threads.Thread.Stoppoints.Stoppoint> getStoppoint() {
            if (stoppoint == null) {
              stoppoint = new ArrayList<Channel.Group.Threads.Thread.Stoppoints.Stoppoint>();
            }
            return this.stoppoint;
          }

          /**
           * <p>
           * Java class for anonymous complex type.
           * 
           * <p>
           * The following schema fragment specifies the expected content contained within this
           * class.
           * 
           * <pre>
           * &lt;complexType>
           *   &lt;simpleContent>
           *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
           *       &lt;attribute name="departure_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
           *       &lt;attribute name="station_code" type="{http://www.w3.org/2001/XMLSchema}int" />
           *       &lt;attribute name="station_code_system" type="{http://www.w3.org/2001/XMLSchema}string" />
           *       &lt;attribute name="station_title" type="{http://www.w3.org/2001/XMLSchema}string" />
           *       &lt;attribute name="arrival_shift" type="{http://www.w3.org/2001/XMLSchema}int" />
           *     &lt;/extension>
           *   &lt;/simpleContent>
           * &lt;/complexType>
           * </pre>
           * 
           * 
           */
          @XmlAccessorType(XmlAccessType.FIELD)
          @XmlType(name = "", propOrder = {"value"})
          public static class Stoppoint implements Serializable {

			private static final long serialVersionUID = 3221820758682887508L;

			@XmlValue
            protected String value;
            @XmlAttribute(name = "departure_shift")
            protected Integer departureShift;
            @XmlAttribute(name = "station_code")
            protected Integer stationCode;
            @XmlAttribute(name = "station_code_system")
            protected String stationCodeSystem;
            @XmlAttribute(name = "station_title")
            protected String stationTitle;
            @XmlAttribute(name = "arrival_shift")
            protected Integer arrivalShift;

            /**
             * Gets the value of the value property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getValue() {
              return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setValue(String value) {
              this.value = value;
            }

            /**
             * Gets the value of the departureShift property.
             * 
             * @return possible object is {@link Integer }
             * 
             */
            public Integer getDepartureShift() {
              return departureShift;
            }

            /**
             * Sets the value of the departureShift property.
             * 
             * @param value allowed object is {@link Integer }
             * 
             */
            public void setDepartureShift(Integer value) {
              this.departureShift = value;
            }

            /**
             * Gets the value of the stationCode property.
             * 
             * @return possible object is {@link Integer }
             * 
             */
            public Integer getStationCode() {
              return stationCode;
            }

            /**
             * Sets the value of the stationCode property.
             * 
             * @param value allowed object is {@link Integer }
             * 
             */
            public void setStationCode(Integer value) {
              this.stationCode = value;
            }

            /**
             * Gets the value of the stationCodeSystem property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getStationCodeSystem() {
              return stationCodeSystem;
            }

            /**
             * Sets the value of the stationCodeSystem property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setStationCodeSystem(String value) {
              this.stationCodeSystem = value;
            }

            /**
             * Gets the value of the stationTitle property.
             * 
             * @return possible object is {@link String }
             * 
             */
            public String getStationTitle() {
              return stationTitle;
            }

            /**
             * Sets the value of the stationTitle property.
             * 
             * @param value allowed object is {@link String }
             * 
             */
            public void setStationTitle(String value) {
              this.stationTitle = value;
            }

            /**
             * Gets the value of the arrivalShift property.
             * 
             * @return possible object is {@link Integer }
             * 
             */
            public Integer getArrivalShift() {
              if (arrivalShift == null) {
                arrivalShift = 0;
              }
              return arrivalShift;
            }

            /**
             * Sets the value of the arrivalShift property.
             * 
             * @param value allowed object is {@link Integer }
             * 
             */
            public void setArrivalShift(Integer value) {
              this.arrivalShift = value;
            }

          }

        }

      }

    }

  }

}
